name: Feature Request
description: Suggest an enhancement or new feature to improve SecureFolderFS
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        ### Please read before you begin!
        > **Warning**
        > Ignoring these instructions may result in your request being closed
        
        We highly value well-written and concise feedback as it simplifies the review process of your proposal.
        Make sure that all fields are filled out and do not miss any information that might be essential with the progress of your request.
  - type: textarea
    attributes:
      label: Describe the feature and how it would impact the app
      description: Try to be precise about the feature or an enhancement. Attach additional screenshots if necessary
    validations:
      required: true
  - type: textarea
    attributes:
      label: Requirements
      description: Provide a scope of the feature and additional considerations
      placeholder: |
        - This proposal will add/enhance X
        - This proposal will replace Y
        - This proposal will not modify Z
    validations:
      required: true
  - type: input
    attributes:
      label: App Version
      description: |
        Please provide your curruent SecureFolderFS version.
        (You can copy the version number by going to Settings > About > Version)
    validations:
      required: true
